### PR TITLE
LRQA-33560 Wait 1 minute for TCK timeout

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
ci:test:tck

**Comment by vsingleton** [comment]
@stiemannkj1 testing this over here:
https://github.com/vsingleton/liferay-portal/pull/82

**Comment by stiemannkj1** [comment]
ci:test:tck

**Comment by stiemannkj1** [comment]
@vsingleton, it seems like the other PR is still using [the 1 second timeout](https://github.com/vsingleton/liferay-portal/pull/82/files#diff-66d24afc65d5a682dc718d87a8b0adeeR1621). I wanted to tests a 1 minute (60 second timeout).

**Comment by vsingleton** [comment]
@stiemannkj1 Every single PR after 81 has been using the timeout=60:
https://github.com/vsingleton/liferay-portal/pull/82
https://github.com/vsingleton/liferay-portal/pull/83
https://github.com/vsingleton/liferay-portal/pull/84
https://github.com/vsingleton/liferay-portal/pull/85

**Pull request closed without merging**
