### PR TITLE
LPS-64093

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@vsingleton can you resend this to me? I fixed a lot of the classes, I only left 2 for you guys to modify, WebXMLDefinitionLoaderTest.java and OrderUtil.java.

There are 2 hard things in programming.. cache invalidation and naming things. The code you guys wrote is very intelligent and creative, and works well (thank you for the test).

However, the naming of the variables lacked tender loving care. I did my best to show by example, a bunch of the renaming... I tried doing the rest of the class, but it was too much. I need you (Vernon) to finish it off and send it back to me.

Also, see modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-test/src/testIntegration/resources/com/liferay/dynamic/data/mapping/dependencies/ddm-form-evaluator-form-values-visible-fields-test-data-1.json

Test files should be xyz-1.xml, not xyz1.xml.

Please resend. Thx guys.

fyi @juangon @rotty3000 fyi

**Comment by juangon** [comment]
@brianchandotcom can you send to me? I did the test part and integrated the OrderUtil.

**Comment by juangon** [comment]
@vsingleton don't worry about this, I am going to make the renaming based on this pull and resend to Brian.

**Comment by juangon** [comment]
Sent here: https://github.com/juangon/liferay-portal/pull/29

**Pull request closed without merging**
